quarkus:
  datasource:
    db-kind: "postgresql"
  hibernate-orm:
    sql-load-script: "import.sql"

"%dev":
  quarkus:
    hibernate-orm:
      database:
        generation: "drop-and-create"
      sql-load-script: "import-dev.sql"
      log:
        sql: true