quarkus:
  datasource:
    db-kind: "postgresql"
  hibernate-orm:
    sql-load-script: "import.sql"

smallrye:
  jwt:
    sign:
      key:
        location: "jwt/private-key.pem"

mp:
  jwt:
    verify:
      publickey:
        location: "jwt/public-key.pem"
      issuer: "https://example.com/issuer"

"%dev":
  quarkus:
    hibernate-orm:
      database:
        generation: "drop-and-create"
      sql-load-script: "import-dev.sql"
      log:
        sql: true

"%test":
  quarkus:
    hibernate-orm:
      sql-load-script: "import-dev.sql"
